### ISSUE TITLE
Ana is constantly saying non sense sentences.

### ISSUE THREAD

**Issue by Barbiche** [JulienBara/Ana#1]
Hello there,

You're project is nice :) However after some time spent learning with a conversation I've made with friends since months, Anabot seems to stuck on weird sentences such as : "Tu savais qu'en Bolivie, ils enterraient un foetus de lama avant de construire une maison ?", or "Sac de couchage". Do you have any idea on what happened ?

Thank you !

**Comment by JulienBara** [comment]
Hi Barbiche,

I am glad to hear that you are using my project and that you are enjoying it :)
It gives me the motivation to continue my work on "it"/"her"!

Keep in mind that Ana learns from what you give her in the conversation. I don't think improving Ana's code may change anything. I suggest you to try hard rebooting your friends, if it doesn't fix, you may try to change them to solve the issue.

I close the issue for the moment, don't hesitate to come back if you have other issues :)
